name: diagnostics

# Field definitions
fields:
    common: &common
        - name: Date
        - name: Study
        - name: Study Link
        - name: Journal
        - name: Study Type

    appendix: &appendix
        - name: Sample
        - name: Sample Text
        - name: Study Population
        - name: Matches
        - name: Entry

# Define queries
Development of a point-of-care test and rapid bed-side tests:
    query: Development of a point-of-care test and rapid bed-side detection methods
    columns:
        - *common
        - *appendix

Diagnosing SARS-COV-2 with antibodies:
    query: diagnose sars-cov-2 antibodies
    columns:
        - *common
        - *appendix

Diagnosing SARS-COV-2 with Nucleic-acid based tech:
    query: diagnose sars-cov-2 nucleic-acid
    columns:
        - *common
        - *appendix
