# Task name
name: materials

# Field definitions
fields:
    common: &common
        - name: Date
        - name: Study
        - name: Study Link
        - name: Journal
        - name: Study Type

    appendix: &appendix
        - name: Sample Size
        - name: Sample Text
        - name: Study Population
        - name: Matches
        - name: Entry

# Define queries
Adhesion to hydrophilic_phobic surfaces:
    query: Persistence hydrophilic, phobic plastic, steel, copper, cardboard
    columns:
        - *common
        - *appendix

Coronavirus susceptibility to heat light and radiation:
    query: coronavirus heat light radiation
    columns:
        - *common
        - *appendix

How long can other HCoV virus remain viable on common surfaces:
    query: Duration viable on surfaces days
    columns:
        - *common
        - *appendix

Persistence of virus on surfaces of different materials:
    query: Persistence on surfaces days
    columns:
        - *common
        - *appendix

Susceptibility to environmental cleaning agents:
    query: Concentration ppm % disinfectant agent inactivate
    columns:
        - *common
        - *appendix

What do we know about viral shedding in blood:
    query: Shedding blood days
    columns:
        - *common
        - {name: Material, constant: Blood}
        - {name: Method, query: rt-pcr confirmed, question: what rna confirmation method used}
        - {name: Days After Onset/Admission (+) Covid-19 Presence (maximum unless otherwise stated), query: shedding blood days}
        - {name: Conclusion, query: stool shedding conclusions findings results, question: What is conclusion on blood shedding}
        - *appendix

What do we know about viral shedding in the nasopharynx:
    query: Shedding nasopharynx days
    columns:
        - *common
        - {name: Material, constant: Nasopharynx}
        - {name: Method, query: rt-pcr confirmed, question: what rna confirmation method used}
        - {name: Days After Onset/Admission (+) Covid-19 Presence (maximum unless otherwise stated), query: shedding nasopharynx days}
        - {name: Conclusion, query: stool shedding conclusions findings results, question: What is conclusion on nasopharynx shedding}
        - *appendix

What do we know about viral shedding in stool:
    query: Shedding stool days
    columns:
        - *common
        - {name: Material, constant: Fecal Matter}
        - {name: Method, query: rt-pcr confirmed, question: what rna confirmation method used}
        - {name: Days After Onset/Admission (+) Covid-19 Presence (maximum unless otherwise stated), query: shedding stool days}
        - {name: Conclusion, query: stool shedding conclusions findings results, question: What is conclusion on stool shedding}
        - *appendix

What do we know about viral shedding in urine:
    query: Shedding urine days
    columns:
        - *common
        - {name: Material, constant: Urine}
        - {name: Method, query: rt-pcr confirmed, question: what rna confirmation method used}
        - {name: Days After Onset/Admission (+) Covid-19 Presence (maximum unless otherwise stated), query: shedding urine days}
        - {name: Conclusion, query: stool shedding conclusions findings results, question: What is conclusion on urine shedding}
        - *appendix
