id: 8
name: risk_factors

# Field definitions
fields:
    common: &common
        - name: Date
        - name: Study
        - name: Study Link
        - name: Journal
        - name: Study Type

    severity: &severity
        - {name: Severe, query: $QUERY, question: "What is $NAME risk statistic"}
        - {name: Severe lower bound, query: $QUERY, question: "What is $NAME range minimum"}
        - {name: Severe upper bound, query: $QUERY, question: "What is $NAME range maximum"}
        - {name: Severe p-value, query: $QUERY, question: "What is the $NAME p-value"}

    appendix: &appendix
        - name: Sample Size
        - name: Sample Text
        - name: Study Population
        - name: Matches
        - name: Entry

    columns: &columns
        - *common
        - *severity
        - *appendix

Age:
    query: Age CI
    columns: *columns

Asthma:
    query: Asthma CI
    columns: *columns

Cancer:
    query: Cancer CI
    columns: *columns

Cardio- and cerebrovascular disease:
    query: Cardio and Cerebrovascular disease CI
    columns: *columns

Cerebrovascular disease:
    query: Cerebrovascular disease CI
    columns: *columns

Chronic digestive disorders:
    query: Digestive disorders CI
    columns: *columns

Chronic kidney disease:
    query: Kidney disease CKD CI
    columns: *columns

Chronic liver disease:
    query: Liver disease CI
    columns: *columns

Chronic respiratory diseases:
    query: Chronic respiratory disease CI
    columns: *columns

COPD:
    query: Chronic obstructive pulmonary disease COPD CI
    columns: *columns

Dementia:
    query: Dementia CI
    columns: *columns

Diabetes:
    query: Diabetes CI
    columns: *columns

Drinking:
    query: Alcohol Abuse CI
    columns: *columns

Endocrine diseases:
    query: Endocrine disease CI
    columns: *columns

Ethnicity_ Hispanic vs. non-Hispanic:
    query: Hispanic race CI
    columns: *columns

Heart Disease:
    query: Heart Disease CI
    columns: *columns

Heart Failure:
    query: Heart Failure CI
    columns: *columns

Hypertension:
    query: Hypertension CI
    columns: *columns

Immune system disorders:
    query: Immune system disorder CI
    columns: *columns

Male gender:
    query: Male CI
    columns: *columns

Overweight or obese:
    query: Overweight obese CI
    columns: *columns

Race_ Black vs. White:
    query: Race black white CI
    columns: *columns

Respiratory system diseases:
    query: Respiratory disease CI
    columns: *columns

Smoking Status:
    query: Smoking smoker ci
    columns: *columns
